# Generated by Django 5.0 on 2024-06-20 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_reqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqtor_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=250)),
                ('previous_details', models.CharField(max_length=300)),
                ('college', models.CharField(max_length=250)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
