# Generated by Django 5.0 on 2024-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_change_reqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_reqs',
            name='status',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='change_reqs',
            name='file_name',
            field=models.CharField(max_length=400),
        ),
    ]
