# Generated by Django 5.0 on 2024-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_change_reqs_status_alter_change_reqs_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_reqs',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
